### ISSUE TITLE
No mention of how to get an API key

### ISSUE THREAD

**Issue by allywilson** [tom-doerr/codex-readme#1]
The script requires an OpenAI key, but it's not mentioned anywhere that it is needed, or how to obtain one (additionally, no mention of the modules needed to install as well).

**Comment by tom-doerr** [comment]
Yes, the reason for this is that the readme was autogenerated and serves as an example for autogenerated readmes. 
I just updated the script so it tells you what modules to install and where to register for Codex.

**Comment by tom-doerr** [comment]
Here's the information:
You can obtain the API key after you get accepted for Codex (https://openai.com/blog/openai-codex/) and install the `openai` module using `pip3 install openai`.

**Comment by pepa65** [comment]
How do I use/apply the key once obtained? I tried using `--tokens` but that didn't seem to be it.

**Comment by tom-doerr** [comment]
It should generate a config file for you where you can enter the key once you run it. The files should be at `~/.config/openaiapirc `.

**Comment by pepa65** [comment]
I had to do `python3 -m pip install openai`, just `pip install openai` didn't work...
