### ISSUE TITLE
The model: `code-davinci-001` does not exist

### ISSUE THREAD

**Issue by crimsonclyde** [tom-doerr/codex-readme#5]
Not entirely sure if this is an "issue" in its classical form, but I run into the error while running the script:

`The model: `code-davinci-001` does not exist` 

Link to an online discussion:
https://community.openai.com/t/the-model-text-davinci-edit-001-does-not-exist/116144/31

Seems to be deprecated and replaced by gpt-3.5-turbo

ChatGPT (self)
`The code-davinci-001 model you're trying to access might have been removed or renamed by OpenAI since my knowledge cutoff date. I suggest checking the OpenAI API documentation to ensure that the model name you're using is correct and supported.`

**Comment by mzvic** [comment]
same error here

**Comment by tom-doerr** [comment]
The default model isn't available anymore, upgraded it to chatgpt.
